version: '3.9'

services:
  fastapi-app:
    build: .
    container_name: fastapi_app
    ports:
      - "8060:8060"  # Map host port to container port
    volumes:
      - .:/app       # Mount local directory to container for live reloading
    environment:
      - PYTHONUNBUFFERED=1  # Ensure logs are output in real-time
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8060", "--reload"]  # Enable reload
    working_dir: /app     # Set working directory explicitly